version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pipeline_db
    environment:
      POSTGRES_DB: pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
